<?php
declare(strict_types=1);
if(session_status()===PHP_SESSION_NONE){session_name('PENDENZ_SESSID');session_start();}
require_once __DIR__.'/../../config.php'; require_once __DIR__.'/../../includes/auth.php'; require_once __DIR__.'/../../includes/authz.php'; require_once __DIR__.'/../../includes/functions.php'; require_once __DIR__.'/bootstrap.php'; require_once __DIR__.'/lib.php';
require_login(); $role=$_SESSION['rolle']??'gast'; if(!in_array($role,['admin','superadmin'],true)){http_response_code(403);exit('Zugriff verweigert');}
nk_bootstrap($mysqli); $h=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$year=(int)($_GET['jahr']??date('Y')); $pid=(int)($_GET['projekt_id']??($_SESSION['current_project_id']??0)); $projects=$mysqli->query('SELECT id,nummer,name FROM projekte ORDER BY name')->fetch_all(MYSQLI_ASSOC); if(!$pid && $projects)$pid=(int)$projects[0]['id'];
$bookings=$pid?nk_load_bookings($mysqli,$pid,$year):[]; $units=[]; if($pid){$st=$mysqli->prepare('SELECT w.id AS wohnung_id, COALESCE(w.flaeche,0) area FROM wohnungen w JOIN objekte o ON o.id=w.objekt_id WHERE o.projekt_id=?'); if($st){$st->bind_param('i',$pid);$st->execute();$units=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();}}
foreach($units as &$u){$u['units']=1;$u['persons']=1;} unset($u); $result=nk_calculate_statement($bookings,$units,($year%4===0?366:365));
?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nebenkostenabrechnung</title><script src="../../assets/js/finance-tables.js?v=20260915.2" defer></script><style>body{font-family:Arial,sans-serif;margin:0;background:#f1f5f9;color:#0f172a}.wrap{max-width:1200px;margin:30px auto;padding:0 18px}.card{background:#fff;border-radius:12px;padding:18px;margin:14px 0;box-shadow:0 2px 8px #0001}label{font-weight:700;margin-right:8px}select,input,button{padding:8px;border:1px solid #cbd5e1;border-radius:6px}button{background:#0f766e;color:#fff;font-weight:700;cursor:pointer}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.kpi{font-size:22px;font-weight:800}.warn{background:#fff7ed;color:#9a3412;padding:10px;border-radius:8px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #e2e8f0;text-align:left}.num{text-align:right}</style></head><body><?php require __DIR__.'/../../includes/nav_dispatch.php'; ?><main class="wrap"><div class="card"><h1>📑 Nebenkostenabrechnung</h1><p>Mieterabrechnung und Eigentümer-/Steuerübersicht für eine Liegenschaft. <a href="../finanzgruppen/index.php?projekt_id=<?=$pid?>">🗂️ Gruppen verwalten</a></p><form method="get"><label>Liegenschaft <select name="projekt_id"><?php foreach($projects as $p):?><option value="<?=$p['id']?>" <?=$pid===$p['id']?'selected':''?>><?=$h(($p['nummer']? $p['nummer'].' - ':'').$p['name'])?></option><?php endforeach;?></select></label><label>Jahr <input type="number" name="jahr" value="<?=$year?>" min="2000" max="2100"></label><button>Berechnen</button></form></div>
<div class="grid"><div class="card"><div>Umlagefähige Kosten</div><div class="kpi">CHF <?=number_format($result['tenant_total'],2,'.',"'")?></div></div><div class="card"><div>Effektiver Steuerabzug</div><div class="kpi">CHF <?=number_format($result['owner_effective'],2,'.',"'")?></div></div><div class="card"><div>Pauschalvergleich (20%)</div><div class="kpi">CHF <?=number_format($result['owner_flat'],2,'.',"'")?></div></div><div class="card"><div>Abzugs-Empfehlung</div><div class="kpi">CHF <?=number_format($result['owner_recommended'],2,'.',"'")?></div></div></div>
<?php if($result['warnings']):?><div class="card warn"><strong>Prüfwarnungen</strong><ul><?php foreach($result['warnings'] as $w):?><li><?=$h($w)?></li><?php endforeach;?></ul></div><?php endif;?>
<div class="card"><h2>Mieterabrechnung je Einheit</h2><table><thead><tr><th>Wohnung</th><th class="num">Umlageanteil</th><th class="num">Akonto</th><th class="num">Saldo</th></tr></thead><tbody><?php foreach($result['by_unit'] as $uid=>$amt):?><tr><td><?=$h($uid)?></td><td class="num">CHF <?=number_format($amt,2,'.',"'")?></td><td class="num">—</td><td class="num">CHF <?=number_format($amt,2,'.',"'")?></td></tr><?php endforeach;if(!$result['by_unit']):?><tr><td colspan="4">Keine umlagefähigen Buchungen in diesem Zeitraum.</td></tr><?php endif;?></tbody></table></div>
<div class="card"><h2>Eigentümer-/Steuerübersicht</h2><table><thead><tr><th>Kategorie</th><th class="num">Betrag</th></tr></thead><tbody><?php foreach($result['owner'] as $k=>$v):?><tr><td><?=$h(ucfirst($k))?></td><td class="num">CHF <?=number_format($v,2,'.',"'")?></td></tr><?php endforeach;?></tbody></table><p class="warn">Steuerliche Behandlung nach Kanton, Privat-/Geschäftsvermögen und Einzelfall prüfen. Die Anzeige ist eine Entscheidungsunterstützung und keine Steuerveranlagung.</p><p><a href="export.php?projekt_id=<?=$pid?>&jahr=<?=$year?>&format=csv">CSV exportieren</a> · <a href="export.php?projekt_id=<?=$pid?>&jahr=<?=$year?>&format=pdf">PDF erzeugen</a></p></div></main></body></html>
