<?php
declare(strict_types=1);
if(session_status()===PHP_SESSION_NONE) session_start();
require_once __DIR__.'/../../config.php'; require_once __DIR__.'/../../includes/auth.php'; require_once __DIR__.'/../../includes/functions.php'; require_once __DIR__.'/../../includes/csrf.php'; require_once __DIR__.'/../nebenkostenabrechnung/bootstrap.php';
require_login(); if(!in_array($_SESSION['rolle']??'', ['admin','superadmin'], true)){http_response_code(403); exit('Zugriff verweigert');}
nk_bootstrap($mysqli); $pid=(int)($_GET['projekt_id']??($_POST['projekt_id']??($_SESSION['current_project_id']??0))); $msg='';
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='save_group'){
  csrf_verify(); $name=trim((string)($_POST['name']??''));
  if($name===''){ $msg='Bitte eine Bezeichnung eingeben.'; } else {
    $projekt=(int)($_POST['projekt_id']??0); $projectVal=isset($_POST["global_template"])?null:($projekt>0?$projekt:null); $tool=in_array($_POST['tool']??'', ['nebenkosten','liegenschaft','beide'],true)?$_POST['tool']:'beide'; $parent=(int)($_POST['parent_id']??0); $parentVal=$parent>0?$parent:null; $color=preg_match('/^#[0-9a-f]{6}$/i',$_POST['color']??'')?$_POST['color']:'#64748b'; $sort=(int)($_POST['sort_order']??100); $alloc=isset($_POST['tenant_allocable'])?1:0; $taxRel=isset($_POST['tax_relevant'])?1:0; $tax=in_array($_POST['tax_class']??'', ['unterhalt','investition','verwaltung','finanzierung','privat','unbekannt'],true)?$_POST['tax_class']:'unbekannt'; $key=in_array($_POST['distribution_key']??'', ['area','units','persons','consumption','direct'],true)?$_POST['distribution_key']:'area';
    $st=$mysqli->prepare('INSERT INTO finance_groups (projekt_id,tool,parent_id,name,color,sort_order,tenant_allocable,tax_relevant,tax_class,distribution_key) VALUES (?,?,?,?,?,?,?,?,?,?)'); $st->bind_param('isissiiiss',$projectVal,$tool,$parentVal,$name,$color,$sort,$alloc,$taxRel,$tax,$key); $st->execute(); $st->close(); $msg='Gruppe gespeichert.';
  }
}
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['action']??'')==='deactivate'){csrf_verify();$id=(int)($_POST['id']??0);$st=$mysqli->prepare('UPDATE finance_groups SET active=0 WHERE id=?');$st->bind_param('i',$id);$st->execute();$st->close();$msg='Gruppe deaktiviert.';}
$projects=$mysqli->query('SELECT id,nummer,name FROM projekte ORDER BY name')->fetch_all(MYSQLI_ASSOC); if(!$pid&&$projects)$pid=(int)$projects[0]['id'];
$st=$mysqli->prepare("SELECT * FROM finance_groups WHERE active=1 AND (projekt_id IS NULL OR projekt_id=?) ORDER BY projekt_id IS NOT NULL DESC,sort_order,name");$st->bind_param('i',$pid);$st->execute();$groups=$st->get_result()->fetch_all(MYSQLI_ASSOC);$st->close();
$PAGE_TITLE='Finanzgruppen'; require_once __DIR__.'/../../includes/header.php'; require_once __DIR__.'/../../includes/nav_dispatch.php';
?><main class="container" style="max-width:1180px;margin:24px auto;padding:0 16px"><div class="card" style="padding:20px"><h1>🗂️ Eigene Finanzgruppen</h1><p>Projektbezogene Gruppen für Nebenkosten- und Liegenschaftsabrechnung. Globale Vorlagen gelten für alle Projekte.</p><?php if($msg):?><div class="alert alert-success"><?=htmlspecialchars($msg)?></div><?php endif;?><form method="get" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><label>Projekt <select name="projekt_id" onchange="this.form.submit()"><?php foreach($projects as $p):?><option value="<?=$p['id']?>" <?=$pid===(int)$p['id']?'selected':''?>><?=htmlspecialchars(($p['nummer']?$p['nummer'].' - ':'').$p['name'])?></option><?php endforeach;?></select></label></form></div>
<div class="card" style="padding:20px"><h2>Neue Gruppe</h2><form method="post" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px"><?=csrf_field()?><input type="hidden" name="action" value="save_group"><input type="hidden" name="projekt_id" value="<?=$pid?>"><label>Name<input name="name" required></label><label>Bereich<select name="tool"><option value="beide">Beide Abrechnungen</option><option value="nebenkosten">Nur Nebenkosten</option><option value="liegenschaft">Nur Liegenschaft</option></select></label><label>Farbe<input type="color" name="color" value="#64748b"></label><label>Reihenfolge<input type="number" name="sort_order" value="100"></label><label>Verteilerschlüssel<select name="distribution_key"><option value="area">Fläche</option><option value="units">Einheiten</option><option value="persons">Personen</option><option value="consumption">Verbrauch</option><option value="direct">Direkt</option></select></label><label>Steuerklasse<select name="tax_class"><option value="unbekannt">Unbekannt</option><option value="unterhalt">Unterhalt</option><option value="investition">Investition</option><option value="verwaltung">Verwaltung</option><option value="finanzierung">Finanzierung</option><option value="privat">Privat</option></select></label><label style="grid-column:1/-1"><input type="checkbox" name="tenant_allocable"> Auf Mieter umlagefähig &nbsp; <input type="checkbox" name="tax_relevant"> Steuerlich relevant &nbsp; <input type="checkbox" name="global_template"> Als globale Vorlage für alle Projekte</label><button type="submit">➕ Gruppe anlegen</button></form></div>
<div class="card" style="padding:20px"><h2>Aktive Gruppen</h2><div style="overflow:auto"><table><thead><tr><th>Name</th><th>Bereich</th><th>Schlüssel</th><th>Umlagefähig</th><th>Steuerklasse</th><th></th></tr></thead><tbody><?php foreach($groups as $g):?><tr><td><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:<?=htmlspecialchars($g['color'])?>"></span> <?=htmlspecialchars($g['name'])?><?=is_null($g['projekt_id'])?' <small>(global)</small>':''?></td><td><?=htmlspecialchars($g['tool'])?></td><td><?=htmlspecialchars($g['distribution_key'])?></td><td><?=$g['tenant_allocable']?'Ja':'Nein'?></td><td><?=htmlspecialchars($g['tax_class'])?></td><td><form method="post" onsubmit="return confirm('Gruppe deaktivieren?')"><?=csrf_field()?><input type="hidden" name="action" value="deactivate"><input type="hidden" name="id" value="<?=$g['id']?>"><input type="hidden" name="projekt_id" value="<?=$pid?>"><button type="submit">Deaktivieren</button></form></td></tr><?php endforeach;if(!$groups):?><tr><td colspan="6">Noch keine Gruppen vorhanden.</td></tr><?php endif;?></tbody></table></div></div></main><?php require_once __DIR__.'/../../includes/footer.php';
